var Zanox, adspace, config, connectId, params, ref, secretKey, zanox;

Zanox = require('../lib/Zanox');

ref = config = require('./config'), connectId = ref.connectId, secretKey = ref.secretKey, adspace = ref.adspace;

zanox = Zanox(connectId, secretKey);

params = {
  adspace: adspace,
  status: 'confirmed'
};

zanox.getAllProgramApplications(params, function(err, data) {
  if (err != null) {
    return console.log('error', err);
  }
  return console.log('%j', data);
});

// ---
// generated by coffee-script 1.9.2
